stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: react-app

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh docker-cli tar
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
  script:
    # Package current directory and copy to EC2
    - tar czf project.tar.gz .
    - scp project.tar.gz ec2-user@$EC2_HOST:~/project.tar.gz

    # SSH into EC2, extract project, build and run
    - ssh ec2-user@$EC2_HOST << EOF
        rm -rf ~/deploy-folder
        mkdir -p ~/deploy-folder
        tar -xzf ~/project.tar.gz -C ~/deploy-folder
        cd ~/deploy-folder
        docker stop $DOCKER_IMAGE || true
        docker rm $DOCKER_IMAGE || true
        docker build -t $DOCKER_IMAGE .
        docker run -d -p 80:80 --name $DOCKER_IMAGE $DOCKER_IMAGE
      EOF
