name: CI/CD Docker Deploy to EC2

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE: chessboard
  EC2_USER: ubuntu
  EC2_HOST: ${{ secrets.EC2_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .

      - name: Archive project
        run: tar czf project.tar.gz .

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
          
          scp project.tar.gz $EC2_USER@$EC2_HOST:~/project.tar.gz
          
          ssh $EC2_USER@$EC2_HOST << EOF
            export DOCKER_IMAGE=chessboard
            rm -rf ~/deploy-folder
            mkdir -p ~/deploy-folder
            tar -xzf ~/project.tar.gz -C ~/deploy-folder
            cd ~/deploy-folder
            docker stop \$DOCKER_IMAGE || true
            docker rm \$DOCKER_IMAGE || true
            docker build -t \$DOCKER_IMAGE .
            docker run -d -p 80:80 --name \$DOCKER_IMAGE \$DOCKER_IMAGE
          EOF
