name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create tarball and upload to EC2
        run: |
          tar --exclude='.git' -czf project.tar.gz . || true
          scp project.tar.gz ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/project.tar.gz

      - name: SSH and Deploy on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            export DOCKER_IMAGE=chessboard
            rm -rf ~/deploy-folder
            mkdir -p ~/deploy-folder
            tar -xzf ~/project.tar.gz -C ~/deploy-folder
            cd ~/deploy-folder
            docker stop $DOCKER_IMAGE || true
            docker rm $DOCKER_IMAGE || true
            docker build -t $DOCKER_IMAGE .
            docker run -d -p 80:80 --name $DOCKER_IMAGE $DOCKER_IMAGE
          EOF
